#!/bin/bash
set -e

# Jellyfin TV Box APK Builder
# Uses Android SDK tools to compile, package, and sign a minimal APK

export ANDROID_HOME=/opt/android-sdk
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=$ANDROID_HOME/build-tools/34.0.0:$ANDROID_HOME/platform-tools:$PATH

PROJECT_DIR=$(dirname "$(readlink -f "$0")")
SRC_DIR="$PROJECT_DIR/src"
OUT_DIR="$PROJECT_DIR/out"
GEN_DIR="$PROJECT_DIR/gen"
DEX_DIR="$PROJECT_DIR/dex"

# Clean
rm -rf "$OUT_DIR" "$GEN_DIR" "$DEX_DIR"
mkdir -p "$OUT_DIR" "$GEN_DIR" "$DEX_DIR"

echo "=== Step 1: Compile resources with aapt2 ==="
aapt2 compile \
  --dir "$PROJECT_DIR/res" \
  -o "$OUT_DIR/resources.zip"

echo "=== Step 2: Link resources ==="
aapt2 link \
  -o "$OUT_DIR/app-unaligned.apk" \
  -I "$ANDROID_HOME/platforms/android-19/android.jar" \
  --manifest "$PROJECT_DIR/AndroidManifest.xml" \
  --java "$GEN_DIR" \
  "$OUT_DIR/resources.zip"

echo "=== Step 3: Compile Java sources ==="
# We need the JSON library from the Android SDK (it's built-in on API 19+)
# The gen dir contains R.java generated by aapt2
javac -source 7 -target 7 \
  -bootclasspath "$ANDROID_HOME/platforms/android-19/android.jar" \
  -d "$DEX_DIR" \
  "$GEN_DIR/com/jellyfin/tvbox/R.java" \
  "$SRC_DIR/com/jellyfin/tvbox/MediaItem.java" \
  "$SRC_DIR/com/jellyfin/tvbox/AppState.java" \
  "$SRC_DIR/com/jellyfin/tvbox/JellyfinClient.java" \
  "$SRC_DIR/com/jellyfin/tvbox/LoginActivity.java" \
  "$SRC_DIR/com/jellyfin/tvbox/MainActivity.java" \
  "$SRC_DIR/com/jellyfin/tvbox/TlsHelper.java" \
  "$SRC_DIR/com/jellyfin/tvbox/StreamingProxy.java" \
  "$SRC_DIR/com/jellyfin/tvbox/PlayerActivity.java"

echo "=== Step 4: Convert to DEX with d8 ==="
mkdir -p "$OUT_DIR/dex"
d8 \
  --lib "$ANDROID_HOME/platforms/android-19/android.jar" \
  --output "$OUT_DIR/dex" \
  --min-api 14 \
  "$DEX_DIR/com/jellyfin/tvbox/"*.class

echo "=== Step 5: Add DEX to APK ==="
cd "$OUT_DIR"
# d8 outputs classes.dex in the output directory
if [ -f "dex/classes.dex" ]; then
  # Use zip to add classes.dex to the APK
  cd "dex" && zip -q "../app-unaligned.apk" "classes.dex" && cd ..
fi
cd "$PROJECT_DIR"

echo "=== Step 6: Zipalign ==="
zipalign -f 4 "$OUT_DIR/app-unaligned.apk" "$OUT_DIR/app-aligned.apk"

echo "=== Step 7: Generate keystore ==="
KEYSTORE="$PROJECT_DIR/debug.keystore"
if [ ! -f "$KEYSTORE" ]; then
  keytool -genkey -v -keystore "$KEYSTORE" \
    -alias jellyfin -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass android -keypass android \
    -dname "CN=JellyfinTV, O=Jellyfin, C=CN" 2>/dev/null
fi

echo "=== Step 8: Sign APK ==="
apksigner sign \
  --ks "$KEYSTORE" \
  --ks-pass pass:android \
  --key-pass pass:android \
  --out "$OUT_DIR/JellyfinTV.apk" \
  "$OUT_DIR/app-aligned.apk"

echo ""
echo "=============================================="
echo "BUILD COMPLETE!"
echo "APK: $OUT_DIR/JellyfinTV.apk"
ls -lh "$OUT_DIR/JellyfinTV.apk"
echo "=============================================="